resourcegroup_name="Mcitterraformrg"
location="Canada Central"
vnet_name="myVNet"
address_space=["10.0.0.0/16"]
webtier_name="web-subnet"
webtier_address_prefixes=["10.0.1.0/24"]
apptier_name="app-subnet"
apptier_address_prefixes=["10.0.2.0/24"]
dbtier_name="db-subnet"
dbtier_address_prefixes=["10.0.3.0/24"]
webtier_nsg_name="web-nsg"
